### ISSUE TITLE
Typo!!

### ISSUE THREAD

**Issue by wataru0** [kult0922/Animating-Arbirary-SkyScene#1]
I found a typo in your demo page. "Ground Trueth" should be "Ground Truth".
https://github.com/kult0922/Animating-Cloud-Images-with-Flow-Style-Transfer/blob/d3989e43c635e99ca015c342baee29623e1e14e2/docs/index.html#L72
Pls fix! lmfao

**Comment by kult0922** [comment]
Thanks!
I fixed it.
